import {
  LayoutDashboardIcon,
  FileTextIcon,
  BookIcon,
  PenLineIcon,
  HeartHandshakeIcon,
  HeartIcon,
  UsersIcon,
  ShieldIcon,
  FolderIcon,
  CodeIcon,
  MessageSquareIcon,
  DollarSignIcon,
  CreditCardIcon,
  BarChartIcon,
  AlertTriangleIcon,
  LockIcon,
  SettingsIcon,
  PersonIcon,
  EyeIcon,
  BellIcon,
  UserCheckIcon,
  MegaphoneIcon,
  CalendarIcon,
  IdCardIcon,
  GridIcon,
  ActivityIcon,
  EyeOffIcon,
  HomeIcon,
  GiftIcon,
  TrendingUpIcon,
  FilmIcon,
  ListIcon,
  StarIcon,
  FlagIcon,
  MicIcon,
  PersonPlusIcon,
  ClockIcon,
  CompassIcon,
  ImageInsertIcon,
} from "@/components/ui/icons";
import type { DashboardConfig } from "./types";

export const adminConfig: DashboardConfig = {
  basePath: "/admin",
  sections: [
    {
      items: [
        {
          kind: "item",
          labelKey: "sidebar.mainDashboard",
          href: "/admin",
          icon: LayoutDashboardIcon,
        },
        {
          kind: "group",
          groupId: "articles",
          labelKey: "sidebar.articles",
          icon: MegaphoneIcon,
          items: [
            {
              kind: "item",
              labelKey: "sidebar.allArticles",
              href: "/admin/articles",
              icon: FileTextIcon,
            },
          ],
        },
        {
          kind: "group",
          groupId: "contributions",
          labelKey: "sidebar.contributions",
          icon: GiftIcon,
          items: [
            {
              kind: "item",
              labelKey: "sidebar.supporters",
              href: "/admin/supporters",
              icon: PersonPlusIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.contributionsAnalytics",
              href: "/admin/contributions-analytics",
              icon: TrendingUpIcon,
            },
          ],
        },
        {
          kind: "group",
          groupId: "management",
          labelKey: "sidebar.management",
          icon: IdCardIcon,
          items: [
            {
              kind: "item",
              labelKey: "sidebar.users",
              href: "/admin/users",
              icon: UsersIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.rolesPermissions",
              href: "/admin/roles",
              icon: ShieldIcon,
            },
          ],
        },
        {
          kind: "group",
          groupId: "content",
          labelKey: "sidebar.content",
          icon: GridIcon,
          items: [
            {
              kind: "item",
              labelKey: "sidebar.contentLibrary",
              href: "/admin/content",
              icon: FolderIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.mediaLibrary",
              href: "/admin/media-library",
              icon: ImageInsertIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.collections",
              href: "/admin/collections",
              icon: GridIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.visualEditor",
              href: "/admin/editor",
              icon: CodeIcon,
            },
          ],
        },
        {
          kind: "group",
          groupId: "magazine",
          labelKey: "sidebar.magazine",
          icon: BookIcon,
          items: [
            {
              kind: "item",
              labelKey: "sidebar.magazinePageEditor",
              href: "/admin/magazine/page-editor",
              icon: ClockIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.magazineIssues",
              href: "/admin/magazine-issues",
              icon: FilmIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.magazineArticles",
              href: "/admin/magazine/articles",
              icon: FileTextIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.residency",
              href: "/admin/residency",
              icon: HomeIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.workshopApplications",
              href: "/admin/workshops",
              icon: StarIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.encounterBookings",
              href: "/admin/encounters",
              icon: CalendarIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.allBooks",
              href: "/admin/books",
              icon: ListIcon,
            },
          ],
        },
        {
          kind: "group",
          groupId: "writers",
          labelKey: "sidebar.writers",
          icon: PenLineIcon,
          items: [
            {
              kind: "item",
              labelKey: "sidebar.allWriters",
              href: "/admin/writers",
              icon: MicIcon,
            },
          ],
        },
        {
          kind: "group",
          groupId: "people",
          labelKey: "sidebar.people",
          icon: PersonIcon,
          items: [
            {
              kind: "item",
              labelKey: "sidebar.allPeople",
              href: "/admin/people",
              icon: PersonIcon,
            },
          ],
        },
        {
          kind: "group",
          groupId: "community",
          labelKey: "sidebar.community",
          icon: HeartHandshakeIcon,
          items: [
            {
              kind: "item",
              labelKey: "sidebar.engagements",
              href: "/admin/engagements",
              icon: HeartIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.messaging",
              href: "/admin/messaging",
              icon: MessageSquareIcon,
            },
          ],
        },
        {
          kind: "group",
          groupId: "business",
          labelKey: "sidebar.business",
          icon: ActivityIcon,
          items: [
            {
              kind: "item",
              labelKey: "sidebar.financePayout",
              href: "/admin/finance",
              icon: DollarSignIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.businessAnalytics",
              href: "/admin/analytics",
              icon: BarChartIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.subscriptions",
              href: "/admin/subscriptions",
              icon: CreditCardIcon,
            },
          ],
        },
        {
          kind: "group",
          groupId: "system",
          labelKey: "sidebar.systemSettings",
          icon: SettingsIcon,
          items: [
            {
              kind: "item",
              labelKey: "sidebar.reportsModeration",
              href: "/admin/reports",
              icon: AlertTriangleIcon,
              badge: 8,
            },
            {
              kind: "item",
              labelKey: "sidebar.securityAuth",
              href: "/admin/security",
              icon: CompassIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.systemSettingsPage",
              href: "/admin/settings",
              icon: FlagIcon,
            },
          ],
        },
        {
          kind: "group",
          groupId: "adminSettings",
          labelKey: "sidebar.adminSettings",
          icon: UserCheckIcon,
          items: [
            {
              kind: "item",
              labelKey: "sidebar.profile",
              href: "/admin/profile",
              icon: PersonIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.availability",
              href: "/admin/availability",
              icon: EyeIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.notifications",
              href: "/admin/notifications",
              icon: BellIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.privacy",
              href: "/admin/privacy",
              icon: EyeOffIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.password",
              href: "/admin/password",
              icon: LockIcon,
            },
            {
              kind: "item",
              labelKey: "sidebar.account",
              href: "/admin/account",
              icon: CreditCardIcon,
            },
          ],
        },
      ],
    },
  ],
};
